# application.yml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.StringTypeHandler
spring:
  datasource:
    password: dengjiehui666
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://101.200.89.66:3306/databasework